### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by MacTirom** [Bimmr/McInfected-Ranks#5]
The Problem is this the rank reset permanently when i have 1250/5000 score its a example. 1 Day later have i only 0/5000 EXP and this error log in the console!

This is the error log. What can i do?

[14:57:15 ERROR]: Could not pass event McInfectedLeaveEvent to McInfected-Ranks v1.1.4
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[craftbukkit.jar:git-Spigot-6d16e64-b105298]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit.jar:git-Spigot-6d16e64-b105298]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [craftbukkit.jar:git-Spigot-6d16e64-b105298]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [craftbukkit.jar:git-Spigot-6d16e64-b105298]
at com.bimmr.mcinfected.IPlayers.IPlayer.leave(IPlayer.java:515) [McInfected.jar:?]
at com.bimmr.mcinfected.Command.SubCommands.LeaveCommand.leave(LeaveCommand.java:20) [McInfected.jar:?]
at com.bimmr.mcinfected.Command.SubCommands.LeaveCommand.execute(LeaveCommand.java:37) [McInfected.jar:?]
at com.bimmr.mcinfected.Command.CHandler.onCommand(CHandler.java:98) [McInfected.jar:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [craftbukkit.jar:git-Spigot-6d16e64-b105298]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [craftbukkit.jar:git-Spigot-6d16e64-b105298]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:640) [craftbukkit.jar:git-Spigot-6d16e64-b105298]
at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1135) [craftbukkit.jar:git-Spigot-6d16e64-b105298]
at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:970) [craftbukkit.jar:git-Spigot-6d16e64-b105298]
at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [craftbukkit.jar:git-Spigot-6d16e64-b105298]
at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [craftbukkit.jar:git-Spigot-6d16e64-b105298]
at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit.jar:git-Spigot-6d16e64-b105298]
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.7.0_71]
at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.7.0_71]
at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:19) [craftbukkit.jar:git-Spigot-6d16e64-b105298]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:714) [craftbukkit.jar:git-Spigot-6d16e64-b105298]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [craftbukkit.jar:git-Spigot-6d16e64-b105298]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [craftbukkit.jar:git-Spigot-6d16e64-b105298]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [craftbukkit.jar:git-Spigot-6d16e64-b105298]
at java.lang.Thread.run(Unknown Source) [?:1.7.0_71]
Caused by: java.lang.NullPointerException
at com.bimmr.mcinfected.MySQL.MySQLManager.set(MySQLManager.java:313) ~[?:?]
at com.bimmr.mcinfected.MySQL.MySQLManager.update(MySQLManager.java:350) ~[?:?]
at me.bimmr.mcinfectedranks.ExpManager.updateData(ExpManager.java:127) ~[?:?]
at me.bimmr.mcinfectedranks.Listeners.PlayerLeave(Listeners.java:175) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_71]
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_71]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_71]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_71]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[craftbukkit.jar:git-Spigot-6d16e64-b105298]
... 23 more

**Comment by Bimmr** [comment]
I've got a new version of McInfected that i'm still testing out, but it should hopefuly fix this issue. I was hoing to have it out this week, but I'm not to sure.

**Comment by Bimmr** [comment]
Would you want to beta test the new version of McInfected?

McInfected 1.2.9
- Cleaned up the MySQLManager class
- Fixed leave locations
- Fixed bug when last human leaves and game doesn't end
- Can now disable/enable the constant actionbar
- Fixed /McInfected Stats <Name>
- Fixed a possible error if no arenas can be voted for
- Fixed a bug in ItemUtil related to the leather
- Eating food now heals you
- Changed up the way the setup command works
- Removed blank line above messages when you perform a command
- Finally got around to updating the Scoreboard system
	- New Event system
	- Configurable Titles
	- Line limit is now 48
	- Runs smoother

**Comment by MacTirom** [comment]
Yeah, i'm interested to testing it.

**Comment by MacTirom** [comment]
I feel honored! :D Thank you :+1:
